### ISSUE TITLE
Netlify deployment

### ISSUE THREAD

**Issue by kaydwithers** [contentful/blog-in-5-minutes#15]
I am deploying my site on Netlify however without the `.contentful.json` file, Netlify can not deploy. I am deploying from my GitHub repo so `.contentful.json` is ignored and for good reason.

However I'm not sure how to get the `.contentful.json` file onto Netlify. Does anyone have any tips please?

**Comment by stefanjudis** [comment]
@kaydwithers can you describe what you're doing exactly. I'm currently building my own site with the exact same setup and netlify works fine. :)

**Comment by kaydwithers** [comment]
Hey @stefanjudis, when I add my GitHub Repository to Netlify, the build on Netlify is failing. 

I think it's failing because `.contentful.json` is not in my GitHub Repository?

Do you mind sharing your steps on how you deployed to Netlify?

My deploy settings are
```
Branch: master
Build command: npm run deploy
Publish directory: dist
```

The error I'm getting on Netlify is
```
Error: Please provide needed Contentful configs:
There are two way to do so:
- define a .contentful.json file (similar to .contentful.sample.json) in the root of this directory
- define environment variables CTF_PERSON_ID, CTF_BLOG_POST_TYPE_ID, CTF_SPACE_ID, CTF_ACCESS_TOKEN
```

**Comment by kaydwithers** [comment]
I read that error again and realised I'm stupid and I should put in the Environment Variables in Netlify.

However after doing that I'm getting a new error

```
12:51:25 AM: > Error! Unexpected error. Please try later. (Authentication error – stdin lacks setRawMode support)
```

Any ideas?

**Comment by kaydwithers** [comment]
I just had to change my build command to the below and it's working! `setRawMode` was a Now thing.
```
Build command: nuxt generate
```

Sorry I'm a bit new to Netlify and Nuxt.

**Comment by stefanjudis** [comment]
@kaydwithers 
Sorry for late response.

🎉  Glad to hear that it works now! :) 

May I ask if there would have been a way to prevent this issue from the project side?

**Comment by kaydwithers** [comment]
It was just my inexperience with Netlify that was the problem, the guide is perfect. It might be worth adding Netlify deployment documentation?

The only thing I struggled with was trying to add newly created Contentful data into my site. I tried to copy the way is was setup with BLOG_TYPE_ID, but I had no idea what I was doing. After a bit of trial and error I eventually worked it out.

**Comment by stefanjudis** [comment]
> The only thing I struggled with was trying to add newly created Contentful data into my site. I tried to copy the way is was setup with BLOG_TYPE_ID, but I had no idea what I was doing. After a bit of trial and error I eventually worked it out.

A tutorial on nuxt.js and how it plays with contentful is in the pipeline and will be released soon. :)

> It might be worth adding Netlify deployment documentation?

I assume you used the CLI guide? There are several ways to come here. ;)
