### ISSUE TITLE
Content Modeling Import timing out

### ISSUE THREAD

**Issue by ebonertz** [contentful/blog-in-5-minutes#23]
The content model import is not working for me. There is no error message returned and the progress wheel just continues to spin.  I believe there is an issue with the download-content-model.js file

I use the instructed command 
npm run import-data -- --space-id YOUR_SPACE_ID --management-token YOUR_CONTENT_MANAGEMENT_ACCESS_TOKEN 

Tried with multiple tokens and no luck.

Can you please verify and fix so I can complete this tutorial? Thanks!

**Comment by stefanjudis** [comment]
@ebonertz Can you please define what your environment is? :) Thx. :)

**Comment by ebonertz** [comment]
Sure I am using MacOS version 10.12.3
Currently using Node 8.0.0
Let me know if there is anything else you need.
