### ISSUE TITLE
Regenerate whenever I change stuff on Contentful?

### ISSUE THREAD

**Issue by applefreak** [contentful/blog-in-5-minutes#26]
Do I have to run the deployment script every time something changes on Contentful?

Thanks!

**Comment by stefanjudis** [comment]
@applefreak Hey! 👋 

Yes. The `deploy` or `generate` script will result in static sites. The way this works with contentful is, that you usually set up a CI service like CircleCI or Travis and trigger a new build with a [Contentful webhook](https://www.contentful.com/developers/docs/concepts/webhooks/) (which fires when you change content).

Or you use something like Netlify which offers the same functionality. :)

This way you can serve static HTML, which result in great performance and scales very well and don't need to generate it on the server side everytime some one visits your site. :)

**Comment by applefreak** [comment]
Thanks for the reply!

I was hoping that if there's a way for the page to auto fetch new resource from Contenful every time the page loads while still using `nuxt generate`. 

Any way to over come this? Or is this the behavior of Nuxt?

**Comment by stefanjudis** [comment]
Well... This goes against the idea of `generate`. The goal of it is to pre-generate files.

For dynamic rendering on the server you can read a bit [here](https://nuxtjs.org/guide#server-rendered-universal-ssr-) and [here](https://nuxtjs.org/guide/commands). `nuxt start` should solve this problem.

But yeah, then you need a node capable service like `now` or something, right?

Hope this helps. :)

**Comment by applefreak** [comment]
Ohh, ok. I see now, thanks!
