### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by m1skam** [contentful/blog-in-5-minutes#27]
I have a simple task.
List of publications and list of authors.
The publication may have several authors, the author may have several publications.
As soon as I create a reference field with the option many and link the publications to the authors and back, I get this error.

```html
       <ul>
        <li v-for="post in posts">
          <h4>Post title: {{ post.fields.title }}</h4>
          <h4>Post authors:</h4>
          <ul>
            <li v-for="person in post.fields.person">
              <h5>Person name: {{ person.fields.name }}</h5>
            </li>
          </ul>
        </li>
      </ul>
```

```javascript
asyncData ({env}) {
    return Promise.all([
      client.getEntries({
        'content_type': env.CTF_BLOG_POST_TYPE_ID,
        order: '-sys.createdAt'
      }),
      client.getEntries({
        'content_type': env.CTF_PERSON_TYPE_ID
      })
    ]).then(([posts, people]) => {
      return {
        posts: posts.items,
        people: people.items
      }
    }).catch(console.error)
  },
```

How can this problem be solved?

**Comment by dsbrianwebster** [comment]
@m1skam how did you end up solving or side stepping this? Encountering the same issue

**Comment by stefanjudis** [comment]
I would assume he changed the content model to not have the circular stucture. :)

In my experience circular references can bring a lot of troubles and I try to avoid then whenever possible.
