### ISSUE TITLE
Misleading advertising

### ISSUE THREAD

**Issue by mbrookes** [contentful/blog-in-5-minutes#29]
A blog in 5 minutes that you create by cloning a github repo is not a blog in 5 minutes.

**Comment by kaydwithers** [comment]
I would say it still is and is not misleading. All the scaffolding and Contentful setup is already done for you. It has been one of the easiest blog setups that I have ever done.

Do you think you could close this issue, as it's not helpful in any way.

**Comment by mbrookes** [comment]
Do you think you could MYOB, as it's not helpful in any way.

**Comment by stefanjudis** [comment]
Hello! 👋 

This repository is the base for our `guide` command included in the [contentful-cli](https://www.npmjs.com/package/contentful-cli) command. 

You see [here](https://github.com/contentful/blog-in-5-minutes/blob/master/docs/GETTING-STARTED.md) what it actually includes.

It is not only a `git clone`, it's rather a guide to onboard new users including:

- a `git clone`
- a structural guidance on how to use contentful with a framework like nuxt
- a complete content model setup 

I'm not really sure, I understand the critique of the marketing practices. Happy to receive feedback if you're willing to elaborate a bit. :)

(but I'm not sure if a GitHub issue is the correct place though)

Thx and let me know if I can help with anything. :)
